Repository thoth-station/init-job, pull requests merged in 2019-10, with the labels that each got.

#211 Index URLs should end with /simple to comply Simple API PEP
  app.py
Labels: approved, size/XS

#213 Automatic update of dependency thoth-common from 0.9.10 to 0.9.11
  Pipfile.lock
Labels: bot

#214 Automatic update of dependency thoth-common from 0.9.11 to 0.9.12
  Pipfile.lock
Labels: bot

#215 Automatic update of dependency thoth-python from 0.6.3 to 0.6.4
  Pipfile.lock
Labels: bot

#220 os specific build logic removed from init-job
  app.py
  pyproject.toml
Labels: approved, do-not-merge/needs-rebase, size/M

#222 Automatic update of dependency thoth-python from 0.6.4 to 0.6.5
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#223 Automatic update of dependency thoth-storages from 0.19.9 to 0.19.10
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#225 Automatic update of dependency thoth-storages from 0.19.10 to 0.19.11
  Pipfile.lock
Labels: bot

#226 Automatic update of dependency thoth-storages from 0.19.11 to 0.19.12
  Pipfile.lock
Labels: bot

#229 updated templates with annotations and param thoth-advise-value
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/job-template.yaml
Labels: approved, size/S

#228 Fix URL to Warehouse API registered
  app.py
Labels: approved, size/XS

#227 initialize OpenShift client only if we really need it
  app.py
Labels: approved, size/XS

#231 Automatic update of dependency thoth-storages from 0.19.13 to 0.19.14
  Pipfile.lock
Labels: bot
