Repository thoth-station/init-job, pull requests merged in 2019-08, with the labels that each got.

#168 Automatic update of dependency thoth-storages from 0.18.0 to 0.18.1
  Pipfile.lock
Labels: bot

#169 Automatic update of dependency thoth-storages from 0.18.1 to 0.18.3
  Pipfile.lock
Labels: bot

#170 Automatic update of dependency thoth-common from 0.9.5 to 0.9.6
  Pipfile.lock
Labels: bot

#171 Automatic update of dependency thoth-storages from 0.18.3 to 0.18.4
  Pipfile.lock
Labels: bot

#172 Automatic update of dependency lxml from 4.4.0 to 4.4.1
  Pipfile.lock
Labels: bot

#174 Automatic update of dependency thoth-storages from 0.18.4 to 0.18.5
  Pipfile.lock
Labels: bot

#173 Start using Thoth in OpenShift's s2i
  .s2i/bin/assemble
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: size/M

#175 Automatic update of dependency thoth-python from 0.6.0 to 0.6.1
  Pipfile.lock
Labels: bot

#177 Initial dependency lock
  Pipfile.lock
Labels: bot, size/XL

#178 Automatic update of dependency thoth-common from 0.9.7 to 0.9.8
  Pipfile.lock
Labels: bot

#179 Automatic update of dependency thoth-storages from 0.18.5 to 0.18.6
  Pipfile.lock
Labels: bot

#180 Added config
  .thoth.yaml
Labels: approved, size/S
