Repository thoth-station/init-job, pull requests merged in 2019-09, with the labels that each got.

#184 Switch from Dgraph to PostgreSQL in deployment
  openshift/job-template.yaml
Labels: approved, size/M

#185 Automatic update of dependency thoth-storages from 0.18.6 to 0.19.0
  Pipfile.lock
Labels: bot

#186 Automatic update of dependency thoth-python from 0.6.1 to 0.6.2
  Pipfile.lock
Labels: bot

#181 Start using Thoth's base image
  .s2i/bin/assemble
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#187 Automatic update of dependency thoth-storages from 0.19.0 to 0.19.1
  Pipfile.lock
Labels: bot

#188 Automatic update of dependency thoth-storages from 0.19.1 to 0.19.2
  Pipfile.lock
Labels: bot

#189 Propagate deployment name for sentry environment
  openshift/job-template.yaml
Labels: approved, size/XS

#190 Automatic update of dependency thoth-storages from 0.19.2 to 0.19.3
  Pipfile.lock
Labels: bot

#192 Enable PyPI and AICoE indexes by default on initialization
  app.py
Labels: approved, size/XS

#193 Automatic update of dependency thoth-storages from 0.19.3 to 0.19.4
  Pipfile.lock
Labels: bot

#194 Adjust logic to new AICoE index structure
  app.py
Labels: approved, size/L

#195 updated the post trigger-build pattern
  .zuul.yaml
Labels: approved, size/S

#196 Automatic update of dependency thoth-common from 0.9.8 to 0.9.9
  Pipfile.lock
Labels: bot

#197 Automatic update of dependency thoth-storages from 0.19.4 to 0.19.5
  Pipfile.lock
Labels: bot

#198 Automatic update of dependency thoth-common from 0.9.9 to 0.9.10
  Pipfile.lock
Labels: bot

#200 PostgreSQL adapter does not provide hosts attribute
  app.py
Labels: approved, size/XS

#201 Automatic update of dependency thoth-storages from 0.19.5 to 0.19.6
  Pipfile.lock
Labels: bot

#202 Automatic update of dependency thoth-python from 0.6.2 to 0.6.3
  Pipfile.lock
Labels: bot

#204 use postgresql hostname from thoth configmap
  openshift/job-template.yaml
Labels: approved, size/XS

#205 Automatic update of dependency thoth-storages from 0.19.6 to 0.19.7
  Pipfile.lock
Labels: bot

#206 Automatic update of dependency thoth-storages from 0.19.7 to 0.19.8
  Pipfile.lock
Labels: bot

#208 Automatic update of dependency thoth-storages from 0.19.8 to 0.19.9
  Pipfile.lock
Labels: bot
