Repository thoth-station/init-job, pull requests merged in 2019-05, with the labels that each got.

#26 Adjust job template to use Dgraph
  openshift/job-template.yaml
Labels: approved

#132 Automatic update of dependency thoth-storages from 0.9.6 to 0.11.4
  Pipfile.lock
Labels: approved, bot

#129 Automatic update of dependency thoth-python from 0.4.6 to 0.5.0
  Pipfile.lock
Labels: approved, bot

#130 Automatic update of dependency lxml from 4.3.1 to 4.3.3
  Pipfile.lock
Labels: approved, bot

#131 Automatic update of dependency thoth-common from 0.7.1 to 0.8.7
  Pipfile.lock
Labels: approved, bot

#133 Automatic update of dependency requests from 2.21.0 to 2.22.0
  Pipfile.lock
Labels: bot

#135 Automatic update of dependency thoth-storages from 0.11.4 to 0.14.0
  Pipfile.lock
Labels: bot
