Repository thoth-station/init-job, pull requests merged in 2019-12, with the labels that each got.

#247 Automatic update of dependency thoth-common from 0.9.19 to 0.9.20
  Pipfile.lock
Labels: bot, size/M

#248 Automatic update of dependency thoth-common from 0.9.20 to 0.9.21
  Pipfile.lock
Labels: bot, size/M

#250 Automatic update of dependency thoth-storages from 0.19.25 to 0.19.26
  Pipfile.lock
Labels: bot, size/S

#251 Automatic update of dependency thoth-storages from 0.19.26 to 0.19.27
  Pipfile.lock
Labels: bot, size/S

#252 Update Thoth configuration file and Thoth's s2i configuration
  .thoth.yaml
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#253 Automatic update of dependency thoth-common from 0.9.21 to 0.9.22
  Pipfile.lock
Labels: bot, size/M

#254 Automatic update of dependency thoth-storages from 0.19.27 to 0.19.30
  Pipfile.lock
Labels: bot, size/M
