Repository thoth-station/init-job, pull requests merged in 2019-06, with the labels that each got.

#137 Automatic update of dependency thoth-storages from 0.14.0 to 0.14.1
  Pipfile.lock
Labels: bot

#138 Automatic update of dependency thoth-common from 0.8.7 to 0.8.11
  Pipfile.lock
Labels: bot

#140 Automatic update of dependency lxml from 4.3.3 to 4.3.4
  Pipfile.lock
Labels: bot

#141 Automatic update of dependency thoth-common from 0.8.11 to 0.9.0
  Pipfile.lock
Labels: bot

#142 Automatic update of dependency thoth-common from 0.9.0 to 0.9.1
  Pipfile.lock
Labels: bot

#143 Automatic update of dependency thoth-storages from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: bot

#144 Automatic update of dependency thoth-storages from 0.14.2 to 0.14.3
  Pipfile.lock
Labels: bot

#145 added schema initialization and updated the job template
  app.py
  openshift/job-template.yaml
Labels: approved, size/S

#147 added `--dry-run` flag
  .gitignore
  Pipfile
  Pipfile.lock
  app.py
Labels: approved, size/L
