Repository thoth-station/init-job, pull requests merged in 2019-11, with the labels that each got.

#232 Automatic update of dependency thoth-storages from 0.19.14 to 0.19.15
  Pipfile.lock
Labels: bot

#233 Move openshift variable to method which uses it
  app.py
Labels: approved, size/XS

#234 Automatic update of dependency thoth-storages from 0.19.15 to 0.19.17
  Pipfile.lock
Labels: bot

#235 Automatic update of dependency thoth-python from 0.6.5 to 0.7.1
  Pipfile.lock
Labels: bot

#236 Automatic update of dependency thoth-storages from 0.19.17 to 0.19.18
  Pipfile.lock
Labels: bot

#237 Automatic update of dependency thoth-storages from 0.19.18 to 0.19.19
  Pipfile.lock
Labels: bot

#238 Automatic update of dependency thoth-common from 0.9.14 to 0.9.15
  Pipfile.lock
Labels: bot

#239 Automatic update of dependency thoth-common from 0.9.15 to 0.9.16
  Pipfile.lock
Labels: bot, size/S

#240 Automatic update of dependency thoth-storages from 0.19.19 to 0.19.22
  Pipfile.lock
Labels: bot, size/S

#241 Automatic update of dependency thoth-storages from 0.19.22 to 0.19.23
  Pipfile.lock
Labels: bot, size/M

#242 Automatic update of dependency thoth-storages from 0.19.23 to 0.19.24
  Pipfile.lock
Labels: bot, size/S

#243 Automatic update of dependency lxml from 4.4.1 to 4.4.2
  Pipfile.lock
Labels: bot, size/M

#244 Automatic update of dependency thoth-common from 0.9.16 to 0.9.17
  Pipfile.lock
Labels: bot, size/L

#245 Automatic update of dependency thoth-common from 0.9.17 to 0.9.19
  Pipfile.lock
Labels: bot, size/M

#246 Automatic update of dependency thoth-storages from 0.19.24 to 0.19.25
  Pipfile.lock
Labels: bot, size/M
