Repository thoth-station/init-job, pull requests merged in 2020-06, with the labels that each got.

#351 Automatic update of dependency thoth-python from 0.9.2 to 0.10.0
  Pipfile.lock
Labels: bot, size/M

#352 Automatic update of dependency requests from 2.23.0 to 2.24.0
  Pipfile.lock
Labels: bot, size/M

#353 Automatic update of dependency thoth-common from 0.13.8 to 0.13.12
  Pipfile.lock
Labels: bot, size/M

#354 Automatic update of dependency thoth-storages from 0.22.12 to 0.23.2
  Pipfile.lock
Labels: bot, size/M

#360 migrated to pre-commit
  .coafile
  .pre-commit-config.yaml
  app.py
Labels: approved

#361 Automatic update of dependency thoth-common from 0.13.12 to 0.13.13
  Pipfile.lock
Labels: approved, bot, size/M

#362 Automatic update of dependency thoth-storages from 0.23.2 to 0.24.0
  Pipfile.lock
Labels: approved, bot, size/M

#365 Adding version manager.
  .thoth.yaml
Labels: approved, size/S

#368 Release of version 0.6.1
  CHANGELOG.md
  thoth/initializer/__init__.py
Labels: approved, bot, size/S
