Repository thoth-station/init-job, pull requests merged in 2020-09, with the labels that each got.

#395 Schedule only one index
  app.py
Labels: approved, size/XS

#398 Automatic update of dependency thoth-common from 0.16.0 to 0.19.0
  Pipfile.lock
Labels: approved, bot, size/L

#400 Release of version 0.7.1
  CHANGELOG.md
  thoth/initializer/__init__.py
Labels: approved, bot, size/XS

#399 Automatic update of dependency thoth-storages from 0.25.0 to 0.25.10
  Pipfile.lock
Labels: approved, bot, size/XS

#397 Automatic update of dependency thoth-python from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: approved, bot, size/XS

#403 Do not use thoth.initializer and rename __service_version__
  app.py
  thoth/initializer/__init__.py
Labels: size/M
