Repository thoth-station/init-job, pull requests merged in 2020-04, with the labels that each got.

#316 Automatic update of dependency thoth-common from 0.12.4 to 0.12.5
  Pipfile.lock
Labels: bot, size/M

#317 Automatic update of dependency thoth-common from 0.12.5 to 0.12.6
  Pipfile.lock
Labels: bot, size/S

#318 added all the packages from the google doc
  hundredDatasciencePackages.yaml
Labels: approved, size/L

#319 Correct package name not on pypi
  hundredDatasciencePackages.yaml
Labels: approved, size/XS

#321 Automatic update of dependency thoth-common from 0.12.6 to 0.12.7
  Pipfile.lock
Labels: bot, size/L

#320 Remove latest version restriction from .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#322 Automatic update of dependency thoth-common from 0.12.7 to 0.12.8
  Pipfile.lock
Labels: bot, size/S

#323 Automatic update of dependency thoth-common from 0.12.8 to 0.12.9
  Pipfile.lock
Labels: bot, size/XS

#325 Add more packages to the list
  hundredDatasciencePackages.yaml
Labels: approved, size/S

#326 Automatic update of dependency thoth-python from 0.9.1 to 0.9.2
  Pipfile.lock
Labels: bot, size/M

#327 new interesting packages
  hundredDatasciencePackages.yaml
Labels: approved, size/XS

#328 Correct packages name from PyPi
  hundredsDatasciencePackages.yaml
Labels: approved, size/XS

#329 Automatic update of dependency thoth-common from 0.12.9 to 0.12.10
  Pipfile.lock
Labels: bot, size/S

#330 Automatic update of dependency thoth-common from 0.12.10 to 0.13.0
  Pipfile.lock
Labels: bot, size/S

#331 Automatic update of dependency thoth-storages from 0.22.7 to 0.22.8
  Pipfile.lock
Labels: bot, size/XS

#332 Automatic update of dependency thoth-common from 0.13.0 to 0.13.1
  Pipfile.lock
Labels: bot, size/S

#333 Automatic update of dependency thoth-storages from 0.22.8 to 0.22.9
  Pipfile.lock
Labels: bot, size/S

#334 add init-job cronJob
  openshift/cronJob-template.yaml
Labels: approved, size/L

#335 redundant use of IMAGE_STREAM_TAG
  openshift/job-template.yaml
Labels: approved, size/XS

#336 adjust history limit for cronjob
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#337 Automatic update of dependency thoth-common from 0.13.1 to 0.13.2
  Pipfile.lock
Labels: bot, size/S
