Repository thoth-station/init-job, pull requests merged in 2020-07, with the labels that each got.

#358 Add more info about init-job and correct some errors in code and cli commands
  app.py
  openshift/buildConfig-template.yaml
  workflows/initializer-workflow.yaml
  workflows/templates/solve-core-packages.yaml
  workflows/templates/solve-data-science-packages.yaml
Labels: approved, size/L

#369 Automatic update of dependency thoth-common from 0.13.13 to 0.14.0
  Pipfile.lock
Labels: approved, bot, size/S

#372 Fix parameter type to open to file with data science packages
  app.py
Labels: approved, size/XS

#371 Fix function signature
  app.py
Labels: approved, size/XS

#370 Remove result-api bits
  app.py
  openshift/job-template.yaml
Labels: approved, size/S

#367 Add missing GitHub issue templates
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
Labels: approved, size/M

#373 Remove templates handled by thoth-application
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
  openshift/job-template.yaml
  workflows/initializer-workflow.yaml
  workflows/templates/initialize-schema.yaml
  workflows/templates/register-indexes-template.yaml
  workflows/templates/solve-core-packages.yaml
  workflows/templates/solve-data-science-packages.yaml
Labels: approved, size/XL

#379 Add missing import
  app.py
Labels: approved, size/XS

#376 Automatic update of dependency lxml from 4.5.1 to 4.5.2
  Pipfile.lock
Labels: approved, bot, size/M

#377 Automatic update of dependency thoth-common from 0.14.0 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/M

#378 Automatic update of dependency thoth-storages from 0.24.0 to 0.24.3
  Pipfile.lock
Labels: approved, bot, size/M

#383 Remove latest versions limitation
  .thothTemplate.yaml
Labels: approved, size/XS

#384 Automatic update of dependency thoth-storages from 0.24.3 to 0.24.4
  Pipfile.lock
Labels: approved, bot, size/S

#388 Add intel-tensorflow to datascience packages
  hundredsDatasciencePackages.yaml
Labels: approved, size/XS

#389 Automatic update of dependency thoth-common from 0.14.2 to 0.16.0
  Pipfile.lock
Labels: approved, bot, size/M

#390 Automatic update of dependency thoth-storages from 0.24.4 to 0.25.0
  Pipfile.lock
Labels: approved, bot, size/M

#392 Release of version 0.7.0
  CHANGELOG.md
  thoth/initializer/__init__.py
Labels: approved, bot, size/S

#393 remove the use-argo function
  app.py
Labels: approved, size/S
