Repository thoth-station/init-job, pull requests merged in 2020-05, with the labels that each got.

#340 Automatic update of dependency lxml from 4.5.0 to 4.5.1
  Pipfile.lock
Labels: bot, size/M

#341 Automatic update of dependency thoth-common from 0.13.3 to 0.13.4
  Pipfile.lock
Labels: bot, size/S

#342 Automatic update of dependency thoth-storages from 0.22.10 to 0.22.11
  Pipfile.lock
Labels: bot, size/M

#343 Automatic update of dependency thoth-common from 0.13.4 to 0.13.5
  Pipfile.lock
Labels: bot, size/XS

#347 Automatic update of dependency thoth-common from 0.13.6 to 0.13.7
  Pipfile.lock
Labels: bot, size/S

#346 Create initializer workflow
  app.py
  hundredsDatasciencePackages.yaml
  workflows/initializer-workflow.yaml
  workflows/templates/initialize-schema.yaml
  workflows/templates/register-indexes-template.yaml
  workflows/templates/solve-core-packages.yaml
  workflows/templates/solve-data-science-packages.yaml
Labels: approved, size/XL

#348 Add init file
  app.py
  thoth/initializer/__init__.py
Labels: approved, size/M

#349 Automatic update of dependency thoth-storages from 0.22.11 to 0.22.12
  Pipfile.lock
Labels: bot, size/S

#350 Automatic update of dependency thoth-common from 0.13.7 to 0.13.8
  Pipfile.lock
Labels: bot, size/S
